### PR TITLE
properly log output of willie in systemd

### PR DESCRIPTION
**Pull request by anarcat**
with the --quiet flag, the verbose core config setting has zero effect
and there would be no way for admins to diagnose bot startup problems.

removing the flag has no harmful effects: willie's output is dutifully
logged to systemd's journal files, according to the proper log levels
defined in the config file. since willie doesn't support syslog
logging (see #658 for that), this is pretty much the *only* way to
have logs of willie's activities and problems outside of IRC.

### CODE REVIEW

**Comment by embolalia** [comment]
Is this still relevant since #658 is done?

**Comment by anarcat** [comment]
that's pretty neat! i'll need to upgrade and test this first...

thanks!

**Comment by anarcat** [comment]
@embolalia so to answer your question: yes and no!

no: it seems that output is silenced *regardless* of whether `--quiet` is used now, which is hardly what i was hoping for. :package: 

yes: since it doesn't matter what if you put `--quiet` or not, why not abstract this away from systemd?

i'm not sure how to fix logging here... it would be nice if this would still go to stdout even if started from systemd...

**Comment by embolalia** [comment]
It doesn't restart if it's misconfigured, which is correct. There's no point in continuing to restart it over and over if it'll never run successfully.

**Comment by anarcat** [comment]
my experience with this is that some situations would make willie disappear. i couldn't find out why (because logs don't show up in `systemctl status`), but the previously mentionned patch fixed that issue for me. it was not a configuration problem, it was a properly configured bot that was running, that would crash and not be restarted by systemd.

**Pull request merged**
