### PR TITLE
[WIP] Additional reddit features, addressing Issue #119

### PR DESCRIPTION
**Pull request by whonut**
I've implemented creation time inclusion and cake day detection, as mentioned in Issue #119. I've also made the module more PEP8 compliant and added an example to .redditor.

Cake days present a bit of a problem. Their exact implementation on reddit is explained here: http://www.reddit.com/r/AdviceAnimals/comments/1v6xam/seriously/cepjnfg (I linked the submission, not the comment in commit 2dbaf77). The API doesn't make accessible a user's last login time, so we cannot delay cake days as reddit.com does. Unfortunately this means that users may have the cake day flair on reddit.com but not be labelled as having their cake day by Willie, or vice versa.

I have yet to add the 'kick on NSFW tag' feature from #119 as I was unsure of exactly what was meant. If @embolalia could clarify their intentions, I'd be happy to work on it.

Feedback on the quality of my code, commits etc. would be greatly appreciated.

### CODE REVIEW

**Comment by embolalia** [comment]
At a quick glance, this all looks good. I'm not too worried about the precision of cake days; what you have is close enough. (Especially since it's documented!)

As for the NSFW kick, I was thinking basically a `.setsfw` or some such thing (we really need guidelines for command names…) would create an entry in the db for the channel. When an NSFW link was posted, the module would check if that setting was enabled for the channel and, if it was, kick the user who posted the reddit link. (I also liked the suggestion in #119 of not showing the link from the submission.)

This is good work (on an issue that has been open for an embarrassingly long time). I'll try it out a bit, maybe this weekend, and then merge it. Thanks for the contribution. ^_^

**Comment by whonut** [comment]
Thanks very much. Do you have a preference for the default value of the SFW 'flag'? The way I have it currently it would default to false because the db returns None for a non-existent entry.

If you want it to default to true, I think it'd be best to write a helper that returns True if there's no value set for SFW. Then you'd just always use that to check the value. I assume you'd want something like that in willie.tools?

**Comment by whonut** [comment]
Apologies. Commit 25d4a51 also contains the getsfw command. I messed up my staging.

**Comment by embolalia** [comment]
Great work. Thanks!

**Pull request merged**
