### PR TITLE
add support for &bitlbee IDENTIFY.

### PR DESCRIPTION
**Pull request by alanpost**
model it after the NickServ support.

### CODE REVIEW

**Comment by alanpost** [comment]
I couldn't find the documentation in the repository, so that has not been updated to reflect a new configuration parameter.  I'm happy to fix the documentation as well, if you can point me in the right direction.

**Comment by embolalia** [comment]
Since it works identically to NickServ, and there are other things that NickServ can be called, I'm closing this in favor of just being able to configure what NickServ is called.

**Comment by alanpost** [comment]
I think that's a fantastic idea, would you like a new patch?

**Comment by tyrope** [comment]
That would be very helpful, @alanpost. Looking forward to it. ;)

**Comment by embolalia** [comment]
It's already done; that's why I closed the PR.

**Pull request closed without merging**
